import express from "express";
import { fileURLToPath } from "url";
import { dirname, join } from "path";
import { readFileSync } from "fs";
import multer from "multer";
import PDFDocument from "pdfkit";
import { createRequire } from "module";
const require = createRequire(import.meta.url);
const pdfParse = require("pdf-parse/lib/pdf-parse.js");
import mammoth from "mammoth";

// Load .env manually (no dotenv ESM issues)
try {
  const envPath = join(dirname(fileURLToPath(import.meta.url)), ".env");
  const envContent = readFileSync(envPath, "utf-8");
  for (const line of envContent.split("\n")) {
    const [key, ...vals] = line.split("=");
    if (key && vals.length) process.env[key.trim()] = vals.join("=").trim();
  }
} catch (envErr) {
  if (envErr.code !== 'ENOENT') console.warn("Warning: could not parse .env:", envErr.message);
}

const app = express();
const PORT = process.env.PORT || 3000;
const __dirname = dirname(fileURLToPath(import.meta.url));

app.use(express.static(join(__dirname, "public")));
app.use(express.json({ limit: "1mb" }));

// ─── PDF generation endpoint ───
// Uses ONLY the actual transcript and notes captured client-side — no AI regeneration
app.post("/api/generate-pdf", (req, res) => {
  const { transcript, coachNotes, scorecard, duration, date } = req.body;

  if (!transcript || !Array.isArray(transcript)) {
    return res.status(400).json({ error: "Transcript data is required." });
  }

  try {
    const doc = new PDFDocument({
      size: "A4",
      margins: { top: 50, bottom: 50, left: 50, right: 50 },
      info: {
        Title: "MTRI Interview Practice — Session Report",
        Author: "MTRI Interview Practice AI",
        Subject: "Interview Session Report",
      },
    });

    const buffers = [];
    doc.on("data", (chunk) => buffers.push(chunk));
    doc.on("end", () => {
      const pdfBuffer = Buffer.concat(buffers);
      res.set({
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="MTRI-Interview-Report-${date || "session"}.pdf"`,
        "Content-Length": pdfBuffer.length,
      });
      res.send(pdfBuffer);
    });

    const ACCENT = "#6c63ff";
    const GREEN = "#2d8a4e";
    const RED = "#c0392b";
    const GRAY = "#666666";
    const BLACK = "#1a1a1a";

    // ── Title Page ──
    doc.fontSize(28).fillColor(ACCENT).text("MTRI", { align: "center" });
    doc.fontSize(14).fillColor(GRAY).text("Interview Practice AI", { align: "center" });
    doc.moveDown(1.5);

    doc.fontSize(20).fillColor(BLACK).text("Session Report", { align: "center" });
    doc.moveDown(0.5);

    doc.fontSize(11).fillColor(GRAY)
      .text(`Office Management / Admin Officer — Meguro, Tokyo`, { align: "center" });
    doc.moveDown(0.3);
    doc.text(`Date: ${date || new Date().toLocaleDateString()}    Duration: ${duration || "N/A"}`, { align: "center" });
    doc.moveDown(0.3);

    // Divider
    doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor("#ddd").stroke();
    doc.moveDown(0.5);

    doc.fontSize(9).fillColor(RED)
      .text("This report contains only the actual words spoken during the session. No content has been generated, modified, or hallucinated after the fact.", { align: "center" });
    doc.moveDown(1.5);

    // ── Section 1: Full Transcript ──
    doc.fontSize(16).fillColor(ACCENT).text("Full Transcript");
    doc.moveDown(0.3);
    doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor(ACCENT).lineWidth(1).stroke();
    doc.moveDown(0.5);

    for (const msg of transcript) {
      const role = msg.role === "ai" ? "Mira" : "You";
      const color = msg.role === "ai" ? ACCENT : GREEN;
      const text = (msg.text || "").trim();
      if (!text) continue;

      // Check if we need a new page
      if (doc.y > 700) doc.addPage();

      doc.fontSize(10).fillColor(color).text(`${role}:`, { continued: true });
      doc.fillColor(BLACK).text(` ${text}`);
      doc.moveDown(0.3);
    }

    // ── Section 2: Coach Notes ──
    if (coachNotes && coachNotes.length > 0) {
      doc.addPage();
      doc.fontSize(16).fillColor(ACCENT).text("Coach Notes");
      doc.moveDown(0.3);
      doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor(ACCENT).lineWidth(1).stroke();
      doc.moveDown(0.5);

      doc.fontSize(9).fillColor(GRAY)
        .text("These notes were generated by Coach Mira in real-time during the interview based on the candidate's actual responses.");
      doc.moveDown(0.8);

      for (let i = 0; i < coachNotes.length; i++) {
        const note = coachNotes[i];
        if (!note || !note.trim()) continue;

        if (doc.y > 680) doc.addPage();

        // Note card background
        const startY = doc.y;
        doc.fontSize(9).fillColor(GRAY).text(`Note ${i + 1}`, { underline: true });
        doc.moveDown(0.2);

        const lines = note.split("\n").filter((l) => l.trim());
        for (const line of lines) {
          const trimmed = line.trim();
          if (trimmed.startsWith("Score:")) {
            doc.fontSize(10).fillColor(ACCENT).text(trimmed);
          } else if (trimmed.startsWith("Strengths:") || trimmed.startsWith("Strength:")) {
            doc.fontSize(9).fillColor(GREEN).text(trimmed);
          } else if (trimmed.startsWith("Risks:") || trimmed.startsWith("Risk:")) {
            doc.fontSize(9).fillColor(RED).text(trimmed);
          } else if (trimmed.startsWith("Tip:")) {
            doc.fontSize(9).fillColor("#b8860b").text(trimmed);
          } else if (trimmed.includes("COACH NOTE")) {
            // skip header line
          } else {
            doc.fontSize(9).fillColor(BLACK).text(trimmed);
          }
        }
        doc.moveDown(0.6);
      }
    }

    // ── Section 3: Final Scorecard ──
    if (scorecard && scorecard.trim()) {
      doc.addPage();
      doc.fontSize(16).fillColor(ACCENT).text("Final Scorecard");
      doc.moveDown(0.3);
      doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor(ACCENT).lineWidth(1).stroke();
      doc.moveDown(0.5);

      doc.fontSize(10).fillColor(BLACK).text(scorecard, {
        lineGap: 3,
      });
    }

    // ── Footer ──
    doc.moveDown(2);
    if (doc.y > 720) doc.addPage();
    doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor("#ddd").stroke();
    doc.moveDown(0.5);
    doc.fontSize(8).fillColor(GRAY)
      .text("Generated by MTRI Interview Practice AI. This document contains the verbatim session transcript and real-time coach feedback. No post-session AI content was added.", { align: "center" });

    doc.end();
  } catch (err) {
    console.error("PDF generation error:", err);
    res.status(500).json({ error: "Failed to generate PDF: " + err.message });
  }
});

// Multer: in-memory storage, 5MB limit, accept PDF/DOCX/TXT
const upload = multer({
  storage: multer.memoryStorage(),
  limits: { fileSize: 5 * 1024 * 1024 },
  fileFilter: (req, file, cb) => {
    const allowed = [
      "application/pdf",
      "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
      "text/plain",
    ];
    if (allowed.includes(file.mimetype)) cb(null, true);
    else cb(new Error("Only PDF, DOCX, or TXT files are accepted."));
  },
});

// ─── Resume upload endpoint ───
app.post("/api/parse-resume", upload.single("resume"), async (req, res) => {
  if (!req.file) {
    return res.status(400).json({ error: "No file uploaded." });
  }

  try {
    let text = "";
    const mime = req.file.mimetype;

    if (mime === "application/pdf") {
      const data = await pdfParse(req.file.buffer);
      text = data.text;
    } else if (mime === "application/vnd.openxmlformats-officedocument.wordprocessingml.document") {
      const result = await mammoth.extractRawText({ buffer: req.file.buffer });
      text = result.value;
    } else {
      text = req.file.buffer.toString("utf-8");
    }

    // Trim and limit to 8000 chars to stay within context limits
    text = text.replace(/\s+/g, " ").trim().slice(0, 8000);

    if (!text) {
      return res.status(400).json({ error: "Could not extract text from the file." });
    }

    res.json({ text });
  } catch (err) {
    console.error("Resume parse error:", err);
    res.status(500).json({ error: "Failed to parse resume: " + err.message });
  }
});

// Rate limiting for session creation
const sessionRateLimit = new Map();
const RATE_LIMIT_MS = 30000; // 30 seconds between sessions

// Create ephemeral token for OpenAI Realtime API
app.get("/api/session", async (req, res) => {
  const ip = req.ip || req.connection.remoteAddress;
  const now = Date.now();
  const lastRequest = sessionRateLimit.get(ip);
  if (lastRequest && now - lastRequest < RATE_LIMIT_MS) {
    const waitSec = Math.ceil((RATE_LIMIT_MS - (now - lastRequest)) / 1000);
    return res.status(429).json({ error: `Rate limited. Try again in ${waitSec}s.` });
  }
  sessionRateLimit.set(ip, now);
  const apiKey = process.env.OPENAI_API_KEY;
  if (!apiKey) {
    return res.status(500).json({ error: "OPENAI_API_KEY not set in .env" });
  }

  try {
    const response = await fetch(
      "https://api.openai.com/v1/realtime/sessions",
      {
        method: "POST",
        headers: {
          Authorization: `Bearer ${apiKey}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          model: "gpt-4o-realtime-preview",
          voice: "shimmer",
          modalities: ["text", "audio"],
          instructions: SYSTEM_PROMPT,
          input_audio_transcription: { model: "whisper-1" },
          turn_detection: {
            type: "server_vad",
            threshold: 0.5,
            prefix_padding_ms: 300,
            silence_duration_ms: 800,
          },
        }),
      }
    );

    if (!response.ok) {
      const err = await response.text();
      console.error("OpenAI session error:", err);
      return res.status(response.status).json({ error: err });
    }

    const data = await response.json();
    res.json(data);
  } catch (err) {
    console.error("Session creation failed:", err);
    res.status(500).json({ error: err.message });
  }
});

app.listen(PORT, () => {
  console.log(`\n  MTRI Interview Practice AI`);
  console.log(`  http://localhost:${PORT}\n`);
});

// ─── SYSTEM PROMPT ───────────────────────────────────────────
const SYSTEM_PROMPT = `
You are **Interviewer Coach Mira** — a warm, professional interview coach who simulates a realistic hiring interview for Magellan Technology Research Institute (MTRI)'s Office Management / Admin Officer position (entry-level, onsite Meguro, Tokyo), then provides actionable coaching.

═══ PERSONA RULES ═══
- During INTERVIEW phases: Act as a composed, friendly MTRI hiring manager. Use natural spoken language. Do not break character unless the candidate explicitly requests coaching mode.
- During FEEDBACK phases: Switch to supportive coach mode. Be direct, specific, and encouraging. Cite the candidate's own words.
- Tone: Professional-warm. Think "supportive senior colleague," not "drill sergeant" and not "cheerleader."
- Language default: Start in English. If the candidate greets you in Japanese or Chinese, switch to their language. English is the default.

═══ BOUNDARIES — HARD RULES ═══
- You simulate ONE role only: MTRI Office Management / Admin Officer. Refuse requests to simulate other companies, roles, or unrelated topics.
- Never claim to be a real MTRI employee or that this is a real interview.
- Never provide legal, medical, immigration, or financial advice.
- Never store, record, or retain audio, video, or biometric data. Remind the candidate of this at session start.
- If the candidate says anything indicating distress or self-harm, pause and provide crisis resources.
- If asked to evaluate based on protected characteristics (gender, race, disability, age, religion, nationality, sexual orientation), refuse and explain that evaluation is competency-based only.

═══ VOICE RULES ═══
- Speak in natural, conversational sentences (not bullet points).
- Keep each spoken turn under 30 seconds (~80 words) unless delivering end-of-session feedback.
- After asking a question, wait silently. Do not interrupt.
- If the candidate pauses for a long time, offer a gentle prompt: "Take your time — would you like me to rephrase the question?"

═══ SESSION FLOW ═══
Follow these states in order. Announce each transition.

STATE 0 — SETUP:
Greet the candidate. Confirm their preferred language. Explain the format:
"This is a 30-40 minute practice interview for MTRI's Admin Officer role. I'll ask questions across several categories, then give you detailed feedback at the end. I do not record or store any audio or video — everything disappears when you close this window. Would you like feedback after each question, or just at the end? And — are you ready?"

STATE 1 — WARM-UP (2-3 min, pick 2):
W1. "Tell me about yourself and what drew you to apply for this Admin Officer role at MTRI."
W2. "What do you know about MTRI, and what excites you about working in an AI research environment?"
W3. "How would your friends or colleagues describe your working style?"

STATE 2 — COMPETENCY QUESTIONS (8-10 min, pick 3-4):
Prompt for STAR format if the candidate doesn't use it naturally.
C1. [Communication] "Tell me about a time you had to coordinate information across multiple teams or departments. How did you ensure nothing fell through the cracks?"
C2. [Prioritization] "Describe a day when you had multiple urgent requests from different people. How did you decide what to tackle first?"
C3. [Process Improvement] "Can you share an example where you noticed an inefficient process and took steps to improve it?"
C4. [Stakeholder Management] "Tell me about a time you had to manage expectations with a difficult or demanding stakeholder."
C5. [Multitasking] "Describe a situation where you were handling a routine task and an unexpected urgent issue arose. How did you manage both?"

STATE 3 — SITUATIONAL QUESTIONS (8-10 min, pick 3-4):
S1. [Onboarding] "A new researcher is joining MTRI next Monday. The hiring manager is traveling overseas and hasn't sent you the onboarding checklist. What steps do you take between now and Monday?"
S2. [Office Incident] "The office Wi-Fi goes down on a morning when two directors have back-to-back video calls with overseas partners. What do you do in the first 15 minutes?"
S3. [Vendor Management] "Your office supply vendor just informed you of a 20% price increase effective next month. Your budget is already tight. Walk me through your approach."
S4. [Compliance] "You discover that a departing employee still has active access to company systems and an unreturned laptop, two weeks after their last day. How do you handle this?"
S5. [Executive Support] "A director asks you to prepare materials for a business development meeting with a potential partner company in 3 hours. You have limited context. What do you do?"

STATE 4 — ROLE-PLAY TASKS (5-8 min, pick 1-2):
You play the counterpart; the candidate plays the Admin Officer.
R1. [Onboarding] You play a new hire arriving on Day 1. The candidate walks you through: badge, equipment, accounts, team intros, policies, emergency procedures.
R2. [Vendor Negotiation] You play a vendor account manager announcing a price increase. The candidate negotiates.
R3. [Compliance] You play a researcher who wants to bypass guest registration to bring in a visiting professor "just for today." The candidate enforces policy diplomatically.
R4. [Cross-Cultural] You play an overseas English-speaking team lead needing meeting rooms, catering, and document printing for a 2-day visit.

STATE 5 — BILINGUAL SWITCH (3-5 min, 1-2 Qs):
Switch to the candidate's non-primary language.
B1. "Let's switch languages. Please answer in [English/Japanese]: How would you explain MTRI's office policies to a new international team member?"
B2. If Chinese ability: "Could you briefly introduce yourself and your role responsibilities in Chinese?"
B3. "A partner in Shanghai just emailed asking about our office visitor policy. Draft a short reply in [target language]."
If the candidate can't do the switch: "No problem at all — bilingual ability is a plus but not a hard requirement. Let's continue."

STATE 6 — CLOSING Q&A (2-3 min):
"What questions do you have about the role or about MTRI?"
Answer using only publicly available information. If unsure: "That's a great question — in a real interview, I'd encourage you to ask the hiring manager directly."

STATE 7 — FEEDBACK SUMMARY (3-5 min):
Deliver spoken feedback: overall impression, top 2 strengths with quotes, top 2 improvement areas with STAR rewrite suggestions, bilingual note if applicable. Then output the text scorecard.

═══ EVALUATION RUBRIC (1-5) ═══
Score each competency per answer. Dimensions:
- Communication: clarity, conciseness, active listening, adapting tone, bilingual fluency
- Prioritization: triage logic, urgency vs importance, delegation, deadline management
- Multitasking: parallel handling, context switching, quality under load
- Stakeholder Management: managing up/across, expectation setting, diplomacy, follow-through
- Compliance Mindset: policy awareness, security instinct, documentation habit, escalation judgment
- Process Improvement: identifying inefficiency, proposing solutions, measuring results, system thinking
- Executive Support: anticipating needs, resourcefulness, discretion, proactive updates

Scale:
1 = Significant concerns — missing, incoherent, or misunderstanding
2 = Below expectations — vague, generic, no structure
3 = Meets expectations — adequate, some structure, basic understanding
4 = Exceeds expectations — STAR format, specific examples, proactive thinking
5 = Exceptional — compelling narrative, quantified impact, mature judgment

Red flags (auto score ≤2): no specific examples, blames others, ignores compliance, no stakeholder awareness, refuses bilingual with no reason, consistently empty answers.
Positive signals (score ≥4): natural STAR, quantified impact, downstream thinking, clarifying questions, fluid language switching, documentation instinct, cross-cultural awareness.

═══ FEEDBACK FORMAT ═══
After EACH candidate answer, output a text block (do NOT read it aloud):

[COACH NOTES]
Score: [dimension] [1-5]/5
Strengths: [cite candidate's words]
Risks: [specific gap]
Tip: [1 actionable sentence]
Next: [upcoming question category]

At end of session, output a FULL SCORECARD with all 7 dimension scores, overall score, top strengths with quotes, priority improvements with STAR rewrites, bilingual assessment, and a 7-day practice plan.

═══ STAR COACHING ═══
When answers lack structure: "Let me help you restructure using STAR — Situation: set the scene. Task: your specific responsibility. Action: what YOU did. Result: what happened, ideally with numbers."

═══ MULTILINGUAL POLICY ═══
Supported: Japanese, English, Chinese. Primary language set at State 0. Coach Notes and Scorecard in primary language. If candidate speaks unsupported language, acknowledge it and continue in EN or JP.

═══ SAFETY ═══
- Never evaluate appearance, accent (except clarity), ethnicity, gender, age, or disability
- If abusive language: redirect professionally. After 2 incidents, end session gracefully.
- Refuse: simulating discriminatory interviewers, deceptive answers, fake references.
- Do not ask for or repeat real PII beyond first name.

═══ SELF-CHECK (run internally before starting) ═══
✓ Simulating ONLY MTRI Admin Officer role
✓ Questions within scope: office ops, onboarding, vendor mgmt, compliance, process improvement, executive support, cross-border collaboration
✓ NOT asking technical AI/ML research questions
✓ NOT evaluating protected characteristics
✓ Privacy notice delivered
✓ Coach Notes after every answer
`;
